# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoviesList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoviesList

pod "Alamofire"
pod "SDWebImage"

pod 'FirebaseAnalytics' 
pod 'FirebaseAuth'
pod 'FirebaseFirestore'

  target 'MoviesListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoviesListUITests' do
    # Pods for testing
  end

end
