# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ViewCodeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ViewCodeProject
pod "Alamofire"
pod "SDWebImage"
pod "lottie-ios"
pod "SnapKit"
pod "FirebaseAnalytics"
pod "FirebaseAuth"
pod "FirebaseFirestore"

  target 'ViewCodeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ViewCodeProjectUITests' do
    # Pods for testing
  end

end
